# Lab 2: numpy


---
*Reham Alharbi*

#### Practice Exercise 1

Create the following NumPy arrays:
1. A 1-D array called zeros having 10 elements and all the elements are set to zero.
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float

In [1]:
import numpy as np

# 1-D array called zeros having 10 elements all set to zero
zeros = np.zeros(10)

# 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# 2-D array called ones having 2 rows and 5 columns, all set to 1, dtype as int
ones = np.ones((2, 5), dtype=int)

# 2-D array called myarray1 created using nested Python lists
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

# 2-D array called myarray2 using arange() with start value = 4, step size 4, dtype as float
myarray2 = np.arange(4, 4*15+1, 4, dtype=float).reshape(3, 5)

# Printing the arrays to verify
print("zeros:", zeros)
print("vowels:", vowels)
print("ones:\n", ones)
print("myarray1:\n", myarray1)
print("myarray2:\n", myarray2)



zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vowels: ['a' 'e' 'i' 'o' 'u']
ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following:
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.
2. Reshape the array ones to have all the 10 elements in a single row.
3. Display the 2nd and 3rd element of the array vowels.
4. Display all elements in the 2nd and 3rd row of the array myarray1.
5. Display the elements in the 1st and 2nd column of the array myarray1.
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
7. Reverse the array of vowels.

In [2]:

# Arrays from the previous question
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 4*15+1, 4, dtype=float).reshape(3, 5)

# 1. Find dimensions, shape, size, data type, and item size of arrays
arrays = [zeros, vowels, ones, myarray1, myarray2]
array_names = ['zeros', 'vowels', 'ones', 'myarray1', 'myarray2']

for name, arr in zip(array_names, arrays):
    print(f"Array: {name}")
    print("  Dimensions:", arr.ndim)
    print("  Shape:", arr.shape)
    print("  Size (total elements):", arr.size)
    print("  Data type:", arr.dtype)
    print("  Item size (in bytes):", arr.itemsize)
    print()

# 2. Reshape the array 'ones' to a single row (10 elements)
ones_reshaped = ones.reshape(1, 10)
print("Reshaped 'ones' array:\n", ones_reshaped)
print()

# 3. Display the 2nd and 3rd element of the array 'vowels'
print("2nd and 3rd element of 'vowels':", vowels[1:3])
print()

# 4. Display all elements in the 2nd and 3rd row of the array 'myarray1'
print("2nd and 3rd row of 'myarray1':\n", myarray1[1:3])
print()

# 5. Display elements in the 1st and 2nd column of the array 'myarray1'
print("1st and 2nd column of 'myarray1':\n", myarray1[:, :2])
print()

# 6. Display elements in the 1st column of the 2nd and 3rd row of 'myarray1'
print("1st column of 2nd and 3rd row of 'myarray1':\n", myarray1[1:3, 0])
print()

# 7. Reverse the array of 'vowels'
vowels_reversed = vowels[::-1]
print("Reversed 'vowels' array:", vowels_reversed)

Array: zeros
  Dimensions: 1
  Shape: (10,)
  Size (total elements): 10
  Data type: float64
  Item size (in bytes): 8

Array: vowels
  Dimensions: 1
  Shape: (5,)
  Size (total elements): 5
  Data type: <U1
  Item size (in bytes): 4

Array: ones
  Dimensions: 2
  Shape: (2, 5)
  Size (total elements): 10
  Data type: int64
  Item size (in bytes): 8

Array: myarray1
  Dimensions: 2
  Shape: (3, 3)
  Size (total elements): 9
  Data type: float64
  Item size (in bytes): 8

Array: myarray2
  Dimensions: 2
  Shape: (3, 5)
  Size (total elements): 15
  Data type: float64
  Item size (in bytes): 8

Reshaped 'ones' array:
 [[1 1 1 1 1 1 1 1 1 1]]

2nd and 3rd element of 'vowels': ['e' 'i']

2nd and 3rd row of 'myarray1':
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

1st and 2nd column of 'myarray1':
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]

1st column of 2nd and 3rd row of 'myarray1':
 [  3.4 -19. ]

Reversed 'vowels' array: ['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3.
2. Add the arrays myarray1 and myarray2.
3. Subtract myarray1 from myarray2 and store the result in a new array.
4. Multiply myarray1 and myarray2 elementwise.
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
6. Divide myarray1 by myarray2.
7. Find the cube of all elements of myarray1 and divide the resulting array by 2.
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [3]:

# Arrays from the previous question
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 4*15+1, 4, dtype=float).reshape(3, 5)

# 1. Divide all elements of array 'ones' by 3
ones_divided = ones / 3
print("Array 'ones' divided by 3:\n", ones_divided)
print()

# 2. Add the arrays 'myarray1' and 'myarray2'
# Ensure the shapes are compatible (reshaping myarray2 if needed)
myarray1_add_myarray2 = myarray1 + myarray2[:3, :3]  # Adjust myarray2 to 3x3 for addition
print("myarray1 + myarray2:\n", myarray1_add_myarray2)
print()

# 3. Subtract 'myarray1' from 'myarray2' and store the result in a new array
myarray_diff = myarray2[:3, :3] - myarray1
print("myarray2 - myarray1:\n", myarray_diff)
print()

# 4. Multiply 'myarray1' and 'myarray2' elementwise
myarray_mult = myarray1 * myarray2[:3, :3]
print("myarray1 * myarray2 (elementwise):\n", myarray_mult)
print()

# 5. Do the matrix multiplication of 'myarray1' and 'myarray2' and store in myarray3
try:
    myarray3 = np.dot(myarray1, myarray2.T)  # matrix multiplication
    print("Matrix multiplication of myarray1 and myarray2 (myarray3):\n", myarray3)
except ValueError as e:
    print("Matrix multiplication error:", e)
print()

# 6. Divide 'myarray1' by 'myarray2'
myarray_div = myarray1 / myarray2[:3, :3]
print("myarray1 / myarray2 (elementwise):\n", myarray_div)
print()

# 7. Find the cube of all elements of 'myarray1' and divide the resulting array by 2
myarray1_cubed = (myarray1 ** 3) / 2
print("Cube of myarray1 divided by 2:\n", myarray1_cubed)
print()

# 8. Find the square root of all elements of 'myarray2' and divide by 2, rounded to two decimal places
myarray2_sqrt = np.sqrt(myarray2)
myarray2_sqrt_div2 = np.round(myarray2_sqrt / 2, 2)
print("Square root of myarray2 divided by 2, rounded to two decimal places:\n", myarray2_sqrt_div2)



Array 'ones' divided by 3:
 [[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]

myarray1 + myarray2:
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]

myarray2 - myarray1:
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]

myarray1 * myarray2 (elementwise):
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]

Matrix multiplication error: shapes (3,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

myarray1 / myarray2 (elementwise):
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]

Cube of myarray1 divided by 2:
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]

Square root of myarray2 divided by 2, rounded to two decimal places:
 [[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]]


Using the arrays created above, write NumPy commands for the following:
1. Find the transpose of ones and myarray2.
2. Sort the array vowels in reverse.
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [4]:
# Arrays from previous question
ones = np.ones((2, 5), dtype=int)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 4*15+1, 4, dtype=float).reshape(3, 5)

# 1. Find the transpose of 'ones' and 'myarray2'
ones_transpose = ones.T
myarray2_transpose = myarray2.T

print("Transpose of 'ones':\n", ones_transpose)
print()
print("Transpose of 'myarray2':\n", myarray2_transpose)
print()

# 2. Sort the array 'vowels' in reverse order
vowels_sorted_reverse = np.sort(vowels)[::-1]

print("Vowels sorted in reverse order:", vowels_sorted_reverse)
print()

# 3. Sort 'myarray1' such that the lowest value in each column appears in the first row, and so on
myarray1_sorted_by_column = np.sort(myarray1, axis=0)

print("myarray1 sorted by columns (lowest values in first row):\n", myarray1_sorted_by_column)


Transpose of 'ones':
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

Transpose of 'myarray2':
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]

Vowels sorted in reverse order: ['u' 'o' 'i' 'e' 'a']

myarray1 sorted by columns (lowest values in first row):
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

In [5]:
# 1. Create a 2-D array called 'myarray4' using arange() with 14 rows and 3 columns
myarray4 = np.arange(-1, -1 + (14 * 3) * 0.25, 0.25).reshape(14, 3)

# 2. Split this array row-wise into 3 equal parts
myarray4_split = np.array_split(myarray4, 3, axis=0)

# 3. Print the results
print("myarray4:\n", myarray4)
print("\nSplit myarray4 into 3 parts:")
for idx, part in enumerate(myarray4_split):
    print(f"Part {idx+1}:\n", part)



myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]

Split myarray4 into 3 parts:
Part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]
Part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]
Part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


Using the myarray4 created in the above questions, write commands for the following:
1. Find the sum of all elements.
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise.
4. Find the max of all elements.
5. Find the min of all elements in each row.
6. Find the mean of all elements in each row.
7. Find the standard deviation column wise.

In [6]:
# Assuming 'myarray4' from the previous question is already created
myarray4 = np.arange(-1, -1 + (14 * 3) * 0.25, 0.25).reshape(14, 3)

# 1. Find the sum of all elements
sum_all_elements = np.sum(myarray4)
print("Sum of all elements in myarray4:", sum_all_elements)
print()

# 2. Find the sum of all elements row-wise
sum_row_wise = np.sum(myarray4, axis=1)
print("Sum of all elements row-wise:\n", sum_row_wise)
print()

# 3. Find the sum of all elements column-wise
sum_column_wise = np.sum(myarray4, axis=0)
print("Sum of all elements column-wise:\n", sum_column_wise)
print()

# 4. Find the max of all elements
max_element = np.max(myarray4)
print("Maximum element in myarray4:", max_element)
print()

# 5. Find the min of all elements in each row
min_each_row = np.min(myarray4, axis=1)
print("Minimum element in each row:\n", min_each_row)
print()

# 6. Find the mean of all elements in each row
mean_each_row = np.mean(myarray4, axis=1)
print("Mean of elements in each row:\n", mean_each_row)
print()

# 7. Find the standard deviation column-wise
std_dev_column_wise = np.std(myarray4, axis=0)
print("Standard deviation column-wise:\n", std_dev_column_wise)


Sum of all elements in myarray4: 173.25

Sum of all elements row-wise:
 [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]

Sum of all elements column-wise:
 [54.25 57.75 61.25]

Maximum element in myarray4: 9.25

Minimum element in each row:
 [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]

Mean of elements in each row:
 [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]

Standard deviation column-wise:
 [3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [7]:
from math import radians, sin, cos, sqrt, atan2

# Function to calculate the distance between two locations using the Haversine formula
def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth's radius in km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

# List of capitals with their coordinates (latitude, longitude)
capitals = {
    "Manama, Bahrain": (26.2235, 50.5876),
    "Kuwait City, Kuwait": (29.3759, 47.9774),
    "Doha, Qatar": (25.276987, 51.520008),
    "Abu Dhabi, UAE": (24.4539, 54.3773),
    "Muscat, Oman": (23.5859, 58.4059),
}

# Riyadh coordinates
riyadh_coords = (24.7136, 46.6753)

# Find the closest capital
closest_city = None
shortest_distance = float('inf')

for city, coords in capitals.items():
    distance = haversine(riyadh_coords[0], riyadh_coords[1], coords[0], coords[1])
    if distance < shortest_distance:
        shortest_distance = distance
        closest_city = city

print(f"The closest capital city to Riyadh is {closest_city}, {shortest_distance:.2f} km away.")


The closest capital city to Riyadh is Manama, Bahrain, 427.10 km away.


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [8]:
# List of capitals with their coordinates (latitude, longitude)
capitals = {
    "Ottawa, Canada": (45.4215, -75.6972),
    "Mexico City, Mexico": (19.4326, -99.1332),
    "Havana, Cuba": (23.1136, -82.3666),
    "San José, Costa Rica": (9.9281, -84.0907),
    "Kingston, Jamaica": (17.9714, -76.7936),
    "Port-au-Prince, Haiti": (18.5948, -72.3072),
    "Nassau, Bahamas": (25.0343, -77.3963),
    "Bogotá, Colombia": (4.6110, -74.0827),
    "Santo Domingo, Dominican Republic": (18.4861, -69.9312),
    "Bridgetown, Barbados": (13.1939, -59.5432),
    "Quito, Ecuador": (0.2299, -78.5249),
}

# Washington, D.C. coordinates
dc_coords = (38.8951, -77.0364)

# Calculate distances using a simplified approach
distances = {
    city: np.sqrt((dc_coords[0] - coords[0])**2 + (dc_coords[1] - coords[1])**2)
    for city, coords in capitals.items()
}

# Sort by distance and get the top 10 closest cities
top_10_closest = sorted(distances, key=distances.get)[:10]

# Print the names of the top 10 capital cities and their coordinates
print("Top 10 closest capital cities to Washington, D.C.:")
for city in top_10_closest:
    print(city)

# Create a NumPy array of coordinates for the top 10 cities
top_10_coordinates = np.array([capitals[city] for city in top_10_closest])

print("\nCoordinates of the top 10 cities (latitude, longitude):")
print(top_10_coordinates)

Top 10 closest capital cities to Washington, D.C.:
Ottawa, Canada
Nassau, Bahamas
Havana, Cuba
Port-au-Prince, Haiti
Kingston, Jamaica
Santo Domingo, Dominican Republic
Mexico City, Mexico
San José, Costa Rica
Bridgetown, Barbados
Bogotá, Colombia

Coordinates of the top 10 cities (latitude, longitude):
[[ 45.4215 -75.6972]
 [ 25.0343 -77.3963]
 [ 23.1136 -82.3666]
 [ 18.5948 -72.3072]
 [ 17.9714 -76.7936]
 [ 18.4861 -69.9312]
 [ 19.4326 -99.1332]
 [  9.9281 -84.0907]
 [ 13.1939 -59.5432]
 [  4.611  -74.0827]]
